server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        # 采样率值介于0到1之间，1则表示全部采集
        probability: 1

eureka:
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 要不要拉取服务
    fetch-registry: true
    # 拉取周期30秒
    registry-fetch-interval-seconds: 30
    service-url:
#      defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版