server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 要不要拉取服务
    fetch-registry: true
    # 拉取周期30秒
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:7001/eureka