server:
  port: 8004
# 服务别名-----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.100.238.247:3306/db2020_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hxp
    password: Jb123456
    druid:
      validation-query: SELECT 1
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181